### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Artucuno** [AntagonistHQ/openprovider.py#71]
Hey,
I was wondering if you have any finished documentation for openprovider.py?

https://openproviderpy.readthedocs.io/en/latest/ref.html is empty.

Thanks!

**Comment by blubber** [comment]
Hi @Artucuno, we don't currently have any documentation and unfortunately I don't really have time to create it (or maintain this implementation for that matter).

**Comment by Artucuno** [comment]
Ah alright, no problem.
